version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "5000:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  web:
    build: .\NewsViewer\.      
    ports:
      - "8000:80"
  consumer:
    build: .\NewsConsumer\.
    depends_on:
      - kafka
  producer:
    build: .\NewsSolution\.
    depends_on:
      - kafka